[project]
name = "adelphos-ap"
version = "0.1.0"
description = "Adelphos, the fractal trust network. Activity Pub implementation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp[speedups]>=3.13.3",
    "argon2-cffi>=25.1.0",
    "cryptography>=46.0.3",
    "fastapi[standard]>=0.125.0",
    "httpx-ws>=0.8.2",
    "pytest>=9.0.2",
    "websockets>=15.0.1",
]

# Source - https://stackoverflow.com/a/50610630
# Posted by hoefling, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-20, License - CC BY-SA 4.0

[tool.pytest.ini_options]
pythonpath = [
  "."
]
